-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL DEFAULT ''::text,
  email text NOT NULL DEFAULT ''::text,
  mobile_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login_at timestamp with time zone,
  theme_preference text CHECK (theme_preference = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
  country text NOT NULL DEFAULT 'YE'::text CHECK (country = ANY (ARRAY['SA'::text, 'YE'::text])),
  free_trial_used boolean NOT NULL DEFAULT false,
  must_change_password boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'user'::app_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.calculations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  employee_name text NOT NULL,
  employer_name text NOT NULL,
  monthly_salary numeric NOT NULL,
  service_years integer NOT NULL DEFAULT 0,
  service_months integer NOT NULL DEFAULT 0,
  day_overtime_hours numeric NOT NULL DEFAULT 0,
  night_overtime_hours numeric NOT NULL DEFAULT 0,
  unused_leave_days numeric NOT NULL DEFAULT 0,
  daily_rate numeric NOT NULL,
  hourly_rate numeric NOT NULL,
  total_service_years numeric NOT NULL,
  eos_benefit numeric NOT NULL,
  day_overtime_amount numeric NOT NULL,
  night_overtime_amount numeric NOT NULL,
  leave_compensation numeric NOT NULL,
  total_due numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  serial_number text,
  currency text NOT NULL DEFAULT 'YER'::text CHECK (currency = ANY (ARRAY['YER'::text, 'SAR'::text, 'USD'::text])),
  service_start_date date,
  service_end_date date,
  payload jsonb,
  CONSTRAINT calculations_pkey PRIMARY KEY (id),
  CONSTRAINT calculations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.page_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  path text NOT NULL,
  referrer text,
  user_agent text,
  user_id uuid,
  session_id text,
  country text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT page_views_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid NOT NULL,
  action text NOT NULL,
  target_type text,
  target_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ip_address text,
  user_agent text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  serial_number text NOT NULL UNIQUE,
  year integer NOT NULL,
  seq integer NOT NULL,
  employee_name text,
  employer_name text,
  monthly_salary numeric,
  service_years integer,
  service_months integer,
  total_amount numeric NOT NULL,
  created_by uuid,
  custom_clauses text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  currency text NOT NULL DEFAULT 'YER'::text CHECK (currency = ANY (ARRAY['YER'::text, 'SAR'::text, 'USD'::text])),
  service_start_date date,
  service_end_date date,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  platform_name text NOT NULL DEFAULT 'منصة حاسبة الحقوق العمالية اليمنية'::text,
  logo_url text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_clauses text,
  report_footer text,
  calculator_access_mode text NOT NULL DEFAULT 'free'::text CHECK (calculator_access_mode = ANY (ARRAY['free'::text, 'premium'::text, 'hybrid'::text])),
  enable_info_currency_conversion boolean NOT NULL DEFAULT false,
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legal_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  category text NOT NULL DEFAULT 'general'::text,
  version integer NOT NULL DEFAULT 1,
  archived boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pdf_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT 'Default'::text,
  watermark text,
  footer text,
  signature_block text,
  disclaimer text,
  verification_statement text,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pdf_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  title text NOT NULL,
  message text,
  severity text NOT NULL DEFAULT 'info'::text,
  link text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  read_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.backups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  snapshot jsonb NOT NULL,
  row_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT backups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lawyers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  slug text NOT NULL UNIQUE,
  photo_url text,
  governorate text NOT NULL,
  city text,
  office_name text,
  phone text,
  whatsapp text,
  email text,
  bio text,
  years_experience integer DEFAULT 0,
  specializations ARRAY DEFAULT '{}'::text[],
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'revoked'::text])),
  is_active boolean NOT NULL DEFAULT true,
  avg_rating numeric NOT NULL DEFAULT 0,
  reviews_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lawyers_pkey PRIMARY KEY (id),
  CONSTRAINT lawyers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.advertisements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  image_url text NOT NULL,
  redirect_url text,
  governorate text,
  position text NOT NULL DEFAULT 'hero'::text CHECK ("position" = ANY (ARRAY['hero'::text, 'rotator'::text])),
  sort_order integer NOT NULL DEFAULT 0,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  description text,
  display_seconds integer NOT NULL DEFAULT 10 CHECK (display_seconds >= 2 AND display_seconds <= 120),
  CONSTRAINT advertisements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  logo_url text,
  account_number text,
  account_holder text,
  instructions text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.knowledge_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legal_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  article_number text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  approval_status text NOT NULL DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by uuid,
  last_review_date timestamp with time zone,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_references_pkey PRIMARY KEY (id),
  CONSTRAINT legal_references_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'admin'::app_role,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id),
  CONSTRAINT admin_users_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  period text NOT NULL CHECK (period = ANY (ARRAY['monthly'::text, 'yearly'::text, 'one_time'::text])),
  price numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'YER'::text CHECK (currency = ANY (ARRAY['YER'::text, 'SAR'::text, 'USD'::text])),
  duration_days integer NOT NULL DEFAULT 30,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  country text,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.free_trial_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mobile_number text NOT NULL UNIQUE,
  user_id uuid,
  used_count integer NOT NULL DEFAULT 0,
  first_used_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone NOT NULL DEFAULT now(),
  email text,
  CONSTRAINT free_trial_usage_pkey PRIMARY KEY (id),
  CONSTRAINT free_trial_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text,
  severity text NOT NULL DEFAULT 'info'::text,
  link text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  price numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  period text NOT NULL DEFAULT 'one_time'::text,
  duration_days integer NOT NULL DEFAULT 0,
  calc_credits integer,
  engines ARRAY NOT NULL DEFAULT ARRAY['sa'::text, 'ye'::text],
  show_details boolean NOT NULL DEFAULT true,
  show_legal_refs boolean NOT NULL DEFAULT true,
  allow_pdf boolean NOT NULL DEFAULT true,
  auto_renew boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  kind text NOT NULL DEFAULT 'manual'::text,
  logo_url text,
  instructions text,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_code text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  starts_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  credits_remaining integer,
  auto_renew boolean NOT NULL DEFAULT false,
  provider_code text,
  provider_ref text,
  payment_method_ref text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sa_regulatory_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  category text NOT NULL DEFAULT 'general'::text,
  label text NOT NULL,
  description text,
  value jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sa_regulatory_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sa_official_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  kind text NOT NULL DEFAULT 'national'::text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sa_official_holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sa_contract_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  rule jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sa_contract_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sa_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  employee_name text,
  employer_name text,
  nationality text,
  job_title text,
  sector text,
  start_date date,
  end_date date,
  total_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  plan_code text,
  input jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'open'::text,
  organization_id uuid,
  branch_id uuid,
  assigned_lawyer_id uuid,
  archived boolean NOT NULL DEFAULT false,
  national_id text,
  contract_type text,
  merged_into uuid,
  CONSTRAINT sa_cases_pkey PRIMARY KEY (id),
  CONSTRAINT sa_cases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT sa_cases_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.referral_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  discount_percent numeric NOT NULL DEFAULT 10,
  credit_per_referral_sar numeric NOT NULL DEFAULT 2,
  credit_per_referral_yer numeric NOT NULL DEFAULT 200,
  commission_percent numeric NOT NULL DEFAULT 10,
  free_tier_1_count integer NOT NULL DEFAULT 10,
  free_tier_1_days integer NOT NULL DEFAULT 30,
  free_tier_2_count integer NOT NULL DEFAULT 25,
  free_tier_2_days integer NOT NULL DEFAULT 90,
  free_tier_3_count integer NOT NULL DEFAULT 50,
  free_tier_3_days integer NOT NULL DEFAULT 365,
  allow_user_change_reward boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  min_withdraw_sar numeric NOT NULL DEFAULT 200,
  min_withdraw_yer numeric NOT NULL DEFAULT 1000,
  CONSTRAINT referral_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  reward_type text NOT NULL DEFAULT 'wallet_credit'::text CHECK (reward_type = ANY (ARRAY['wallet_credit'::text, 'free_subscription'::text, 'commission'::text])),
  is_active boolean NOT NULL DEFAULT true,
  reward_chosen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wallet_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  currency text NOT NULL CHECK (currency = ANY (ARRAY['SAR'::text, 'YER'::text])),
  balance numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallet_balances_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL CHECK (currency = ANY (ARRAY['SAR'::text, 'YER'::text])),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['referral_credit'::text, 'referral_commission'::text, 'admin_adjust'::text, 'spend'::text, 'payout'::text])),
  reference_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.countries (
  code text NOT NULL,
  name_ar text NOT NULL,
  name_en text NOT NULL,
  flag text NOT NULL DEFAULT ''::text,
  currency text NOT NULL DEFAULT 'SAR'::text,
  engine text NOT NULL DEFAULT 'sa'::text,
  calculator_path text NOT NULL DEFAULT '/calculator'::text,
  description_ar text,
  description_en text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  timezone text DEFAULT 'Asia/Riyadh'::text,
  language text DEFAULT 'ar'::text,
  employment_law_name text,
  social_insurance_law text,
  legislator text,
  status text NOT NULL DEFAULT 'active'::text,
  CONSTRAINT countries_pkey PRIMARY KEY (code)
);
CREATE TABLE public.unpaid_salary_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT unpaid_salary_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.case_calculations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  country text NOT NULL DEFAULT 'SA'::text,
  rule_version text,
  calculation_version integer NOT NULL DEFAULT 1,
  currency text NOT NULL DEFAULT 'SAR'::text,
  total_salary numeric NOT NULL DEFAULT 0,
  total_leave numeric NOT NULL DEFAULT 0,
  total_sick_leave numeric NOT NULL DEFAULT 0,
  total_maternity numeric NOT NULL DEFAULT 0,
  total_insurance numeric NOT NULL DEFAULT 0,
  total_gratuity numeric NOT NULL DEFAULT 0,
  total_compensation numeric NOT NULL DEFAULT 0,
  total_other numeric NOT NULL DEFAULT 0,
  total_rights numeric NOT NULL DEFAULT 0,
  total_paid_rights numeric NOT NULL DEFAULT 0,
  total_excluded_rights numeric NOT NULL DEFAULT 0,
  final_claim_amount numeric NOT NULL DEFAULT 0,
  confidence_score integer NOT NULL DEFAULT 0,
  calculation_status text NOT NULL DEFAULT 'pending'::text,
  blocked_reason text,
  engines jsonb,
  results jsonb,
  eligibility jsonb,
  exceptions jsonb,
  conflicts jsonb,
  formulas jsonb,
  snapshot jsonb,
  calculation_started_at timestamp with time zone,
  calculation_completed_at timestamp with time zone,
  calculated_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_calculations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  legal_name text,
  country_code text,
  currency text DEFAULT 'SAR'::text,
  timezone text DEFAULT 'Asia/Riyadh'::text,
  language text DEFAULT 'ar'::text,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_code text NOT NULL UNIQUE,
  role_name text NOT NULL,
  description text,
  system_role boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  permission_code text NOT NULL UNIQUE,
  permission_name text NOT NULL,
  module text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  setting_key text NOT NULL,
  setting_value text,
  data_type text NOT NULL DEFAULT 'string'::text,
  module text,
  label text,
  is_encrypted boolean NOT NULL DEFAULT false,
  updated_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (setting_key)
);
CREATE TABLE public.webhook_endpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  url text NOT NULL,
  events ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  secret_hint text,
  is_active boolean NOT NULL DEFAULT true,
  last_status integer,
  last_delivery_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_endpoints_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ip_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ip_value text NOT NULL,
  rule_type text NOT NULL DEFAULT 'blacklist'::text,
  note text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ip_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  severity text NOT NULL DEFAULT 'info'::text,
  alert_type text NOT NULL,
  message text NOT NULL,
  user_id uuid,
  ip_address text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  feature text NOT NULL,
  model text,
  document_type text,
  tokens_used integer,
  latency_ms integer,
  success boolean NOT NULL DEFAULT true,
  quality_rating integer,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_usage_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_dispatches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel text NOT NULL,
  target text,
  audience text NOT NULL DEFAULT 'all'::text,
  subject text,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'queued'::text,
  error_message text,
  sent_by uuid,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_dispatches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legal_rule_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL,
  rule_key text NOT NULL,
  version text NOT NULL,
  title text,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  effective_from date,
  effective_to date,
  status text NOT NULL DEFAULT 'draft'::text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_rule_versions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legal_systems (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL,
  system_code text NOT NULL,
  system_name text NOT NULL,
  system_type text NOT NULL DEFAULT 'labor_law'::text,
  version text NOT NULL DEFAULT '1.0'::text,
  effective_date date NOT NULL DEFAULT CURRENT_DATE,
  expiry_date date,
  authority text,
  notes text,
  status text NOT NULL DEFAULT 'active'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_systems_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rule_formulas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  formula_code text NOT NULL,
  formula_name text NOT NULL,
  formula_expression text NOT NULL,
  variables jsonb NOT NULL DEFAULT '[]'::jsonb,
  return_type text NOT NULL DEFAULT 'number'::text,
  description text,
  version text NOT NULL DEFAULT '1.0'::text,
  status text NOT NULL DEFAULT 'draft'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rule_formulas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rule_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rule_id uuid,
  rule_code text,
  action text NOT NULL,
  old_version text,
  new_version text,
  snapshot jsonb,
  change_reason text,
  changed_by uuid,
  approved_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rule_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rule_test_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL DEFAULT 'SA'::text,
  case_name text NOT NULL,
  rule_code text,
  input_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  expected_output jsonb,
  is_baseline boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rule_test_cases_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_withdrawals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'YER'::text,
  method text,
  account_details text,
  status text NOT NULL DEFAULT 'pending'::text,
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_withdrawals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lawyer_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lawyer_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['license'::text, 'professional'::text, 'other'::text])),
  file_url text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lawyer_documents_pkey PRIMARY KEY (id),
  CONSTRAINT lawyer_documents_lawyer_id_fkey FOREIGN KEY (lawyer_id) REFERENCES public.lawyers(id)
);
CREATE TABLE public.lawyer_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lawyer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  is_hidden boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lawyer_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT lawyer_reviews_lawyer_id_fkey FOREIGN KEY (lawyer_id) REFERENCES public.lawyers(id),
  CONSTRAINT lawyer_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ad_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ad_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['impression'::text, 'click'::text])),
  session_id text,
  path text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ad_events_pkey PRIMARY KEY (id),
  CONSTRAINT ad_events_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES public.advertisements(id)
);
CREATE TABLE public.knowledge_articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  excerpt text,
  body text NOT NULL DEFAULT ''::text,
  tags ARRAY DEFAULT '{}'::text[],
  is_published boolean NOT NULL DEFAULT false,
  seo_title text,
  seo_description text,
  views integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_articles_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_articles_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.knowledge_categories(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text])),
  starts_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  activated_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT subscriptions_activated_by_fkey FOREIGN KEY (activated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.subscription_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid,
  payment_method_id uuid,
  full_name text,
  mobile_number text,
  transfer_reference text,
  receipt_url text,
  amount numeric,
  currency text NOT NULL DEFAULT 'YER'::text CHECK (currency = ANY (ARRAY['YER'::text, 'SAR'::text, 'USD'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  referral_code text,
  discount_amount numeric,
  wallet_used numeric NOT NULL DEFAULT 0,
  CONSTRAINT subscription_requests_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT subscription_requests_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT subscription_requests_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id),
  CONSTRAINT subscription_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.billing_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  plan_code text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  status text NOT NULL DEFAULT 'pending'::text,
  provider_code text NOT NULL DEFAULT 'manual_transfer'::text,
  provider_txn_id text,
  payment_method_ref text,
  receipt_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  referral_code text,
  discount_amount numeric,
  CONSTRAINT billing_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT billing_transactions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.billing_subscriptions(id)
);
CREATE TABLE public.sa_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_number text NOT NULL UNIQUE,
  version integer NOT NULL DEFAULT 1,
  case_id uuid,
  user_id uuid NOT NULL,
  plan_code text NOT NULL,
  employee_label text,
  employer_label text,
  net_total numeric NOT NULL DEFAULT 0,
  gross_total numeric NOT NULL DEFAULT 0,
  deductions_total numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  document jsonb NOT NULL,
  checksum text NOT NULL,
  downloads integer NOT NULL DEFAULT 0,
  archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sa_reports_pkey PRIMARY KEY (id),
  CONSTRAINT sa_reports_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.sa_cases(id)
);
CREATE TABLE public.sa_case_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid,
  user_id uuid NOT NULL,
  step text NOT NULL,
  decision text NOT NULL,
  reason text,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sa_case_audit_pkey PRIMARY KEY (id),
  CONSTRAINT sa_case_audit_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.sa_cases(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code_id uuid NOT NULL,
  referrer_id uuid NOT NULL,
  referred_user_id uuid NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'registered'::text CHECK (status = ANY (ARRAY['registered'::text, 'converted'::text])),
  order_amount numeric,
  discount_amount numeric,
  currency text,
  converted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_code_id_fkey FOREIGN KEY (code_id) REFERENCES public.referral_codes(id)
);
CREATE TABLE public.case_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  country_code text NOT NULL DEFAULT 'SA'::text,
  status text NOT NULL DEFAULT 'draft'::text,
  current_step integer NOT NULL DEFAULT 1,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT case_drafts_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code)
);
CREATE TABLE public.calculation_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  calculation_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  module_name text NOT NULL,
  step_number integer NOT NULL DEFAULT 0,
  rule_applied text,
  formula_used text,
  input_data jsonb,
  output_data jsonb,
  execution_time_ms integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'success'::text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calculation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT calculation_logs_calculation_id_fkey FOREIGN KEY (calculation_id) REFERENCES public.case_calculations(id)
);
CREATE TABLE public.case_final_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  calculation_id uuid,
  report_number text NOT NULL,
  report_type text NOT NULL DEFAULT 'full'::text,
  report_language text NOT NULL DEFAULT 'ar'::text,
  country text NOT NULL DEFAULT 'SA'::text,
  currency text NOT NULL DEFAULT 'SAR'::text,
  generated_by uuid,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  rule_version text,
  system_version text,
  calculation_version integer,
  confidence_score integer NOT NULL DEFAULT 0,
  total_rights numeric NOT NULL DEFAULT 0,
  total_paid numeric NOT NULL DEFAULT 0,
  total_excluded numeric NOT NULL DEFAULT 0,
  final_balance numeric NOT NULL DEFAULT 0,
  options jsonb,
  document jsonb,
  file_pdf text,
  file_docx text,
  file_xlsx text,
  file_html text,
  file_json text,
  qr_code_hash text,
  digital_signature_hash text,
  share_token text,
  archived boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_final_reports_pkey PRIMARY KEY (id),
  CONSTRAINT case_final_reports_calculation_id_fkey FOREIGN KEY (calculation_id) REFERENCES public.case_calculations(id)
);
CREATE TABLE public.calculation_validations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  calculation_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  validation_type text NOT NULL,
  severity text NOT NULL DEFAULT 'info'::text,
  message text NOT NULL,
  related_module text,
  resolved boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calculation_validations_pkey PRIMARY KEY (id),
  CONSTRAINT calculation_validations_calculation_id_fkey FOREIGN KEY (calculation_id) REFERENCES public.case_calculations(id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  country_code text,
  city text,
  currency text DEFAULT 'SAR'::text,
  timezone text DEFAULT 'Asia/Riyadh'::text,
  language text DEFAULT 'ar'::text,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  key_prefix text NOT NULL,
  key_hash text NOT NULL,
  scopes ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  rate_limit_per_min integer NOT NULL DEFAULT 60,
  organization_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  last_used_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.feature_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  flag_key text NOT NULL,
  description text,
  enabled boolean NOT NULL DEFAULT false,
  country_code text,
  plan_code text,
  organization_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feature_flags_pkey PRIMARY KEY (id),
  CONSTRAINT feature_flags_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.admin_role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT admin_role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.admin_roles(id),
  CONSTRAINT admin_role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.admin_permissions(id)
);
CREATE TABLE public.legal_articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL,
  system_id uuid,
  article_number text NOT NULL,
  article_title text NOT NULL,
  article_text text NOT NULL,
  interpretation text,
  source_url text,
  version text NOT NULL DEFAULT '1.0'::text,
  effective_date date NOT NULL DEFAULT CURRENT_DATE,
  expiry_date date,
  status text NOT NULL DEFAULT 'active'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_articles_pkey PRIMARY KEY (id),
  CONSTRAINT legal_articles_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.legal_systems(id)
);
CREATE TABLE public.referral_rewards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referral_id uuid,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['wallet_credit'::text, 'commission'::text, 'free_subscription'::text])),
  amount numeric,
  currency text,
  free_days integer,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'granted'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_rewards_pkey PRIMARY KEY (id),
  CONSTRAINT referral_rewards_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id)
);
CREATE TABLE public.case_overtime (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  start_date date,
  end_date date,
  period_label text,
  hours numeric NOT NULL DEFAULT 0,
  reason text,
  notes text,
  amount numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_overtime_pkey PRIMARY KEY (id),
  CONSTRAINT case_overtime_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_final_settlement (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  has_settlement text NOT NULL DEFAULT 'no'::text,
  settlement_number text,
  settlement_type text,
  settlement_date date,
  signing_date date,
  signing_place text,
  settlement_language text DEFAULT 'ar'::text,
  signature_status text DEFAULT 'no'::text,
  digital_signature_type text,
  digital_signature_provider text,
  digital_signature_reference text,
  digital_signature_date date,
  settlement_file text,
  settlement_file_type text,
  ai_analysis_status text DEFAULT 'not_run'::text,
  ai_analysis jsonb,
  legal_analysis_status text DEFAULT 'not_run'::text,
  legal_analysis jsonb,
  mentioned_rights jsonb,
  waived_rights jsonb,
  covers_all_rights boolean NOT NULL DEFAULT false,
  under_dispute boolean NOT NULL DEFAULT false,
  court_ruling_after boolean NOT NULL DEFAULT false,
  court_ruling_reference text,
  total_settlement_amount numeric,
  currency text NOT NULL DEFAULT 'SAR'::text,
  approved boolean NOT NULL DEFAULT false,
  approved_at timestamp with time zone,
  legal_rule_version text,
  warnings jsonb,
  analysis jsonb,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_final_settlement_pkey PRIMARY KEY (id),
  CONSTRAINT case_final_settlement_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_maternity_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  gender text NOT NULL DEFAULT 'female'::text,
  had_pregnancy boolean NOT NULL DEFAULT false,
  pregnancy_start_date date,
  delivery_date date,
  actual_delivery_date date,
  delivery_type text,
  early_delivery boolean NOT NULL DEFAULT false,
  multiple_birth text,
  newborn_deceased boolean NOT NULL DEFAULT false,
  medical_complications boolean NOT NULL DEFAULT false,
  has_medical_document boolean NOT NULL DEFAULT false,
  medical_document_type text,
  medical_report_file text,
  ended_during_protection boolean NOT NULL DEFAULT false,
  termination_reason text,
  termination_date date,
  termination_party text,
  termination_proof_file text,
  wage_changed boolean NOT NULL DEFAULT false,
  wage_basis text NOT NULL DEFAULT 'last_actual_wage'::text,
  returned_to_work boolean NOT NULL DEFAULT false,
  is_nursing boolean NOT NULL DEFAULT false,
  daily_wage numeric NOT NULL DEFAULT 0,
  total_due numeric NOT NULL DEFAULT 0,
  total_paid numeric NOT NULL DEFAULT 0,
  excluded_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_maternity_summary_pkey PRIMARY KEY (id),
  CONSTRAINT case_maternity_summary_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_termination (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  employment_status text NOT NULL DEFAULT 'unknown'::text,
  termination_reason text,
  termination_category text,
  reason_details text,
  incident_description text,
  incident_date date,
  initiated_by text,
  termination_date date,
  last_working_day date,
  effective_termination_date date,
  notice_given boolean NOT NULL DEFAULT false,
  notice_date date,
  notice_period_days integer,
  notice_method text,
  has_document boolean NOT NULL DEFAULT false,
  legal_analysis_status text,
  legal_warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  applied_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_termination_pkey PRIMARY KEY (id),
  CONSTRAINT case_termination_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_leave_taken (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  service_year integer,
  start_date date,
  end_date date,
  days numeric NOT NULL DEFAULT 0,
  leave_type text NOT NULL DEFAULT 'annual'::text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_leave_taken_pkey PRIMARY KEY (id),
  CONSTRAINT case_leave_taken_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_maternity_leaves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  contract_id uuid,
  pregnancy_start_date date,
  delivery_date date,
  leave_start date,
  leave_end date,
  return_to_work_date date,
  leave_days numeric NOT NULL DEFAULT 0,
  extended boolean NOT NULL DEFAULT false,
  extension_reason text,
  extension_days numeric NOT NULL DEFAULT 0,
  has_document boolean NOT NULL DEFAULT false,
  medical_report_file text,
  daily_wage numeric NOT NULL DEFAULT 0,
  compensation_rate numeric NOT NULL DEFAULT 0,
  compensation_amount numeric NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  payment_method text,
  payment_date date,
  payment_proof_file text,
  currency text NOT NULL DEFAULT 'SAR'::text,
  applied_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_maternity_leaves_pkey PRIMARY KEY (id),
  CONSTRAINT case_maternity_leaves_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_social_insurance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  is_subject text NOT NULL DEFAULT 'unknown'::text,
  exemption_reason text,
  registration_number text,
  registration_status text NOT NULL DEFAULT 'not_registered'::text,
  registration_date date,
  coverage_start_date date,
  coverage_end_date date,
  nationality_category text NOT NULL DEFAULT 'citizen'::text,
  employment_category text NOT NULL DEFAULT 'full_time'::text,
  sector text NOT NULL DEFAULT 'private'::text,
  insurable_wage numeric NOT NULL DEFAULT 0,
  employee_contribution_rate numeric NOT NULL DEFAULT 0,
  employer_contribution_rate numeric NOT NULL DEFAULT 0,
  employee_contribution_amount numeric NOT NULL DEFAULT 0,
  employer_contribution_amount numeric NOT NULL DEFAULT 0,
  total_contribution numeric NOT NULL DEFAULT 0,
  total_due numeric NOT NULL DEFAULT 0,
  total_paid numeric NOT NULL DEFAULT 0,
  total_difference numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  payment_date date,
  payment_reference text,
  payment_proof_file text,
  currency text NOT NULL DEFAULT 'SAR'::text,
  applied_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_social_insurance_pkey PRIMARY KEY (id),
  CONSTRAINT case_social_insurance_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_annual_leave (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  service_year integer NOT NULL,
  period_start date,
  period_end date,
  period_days numeric NOT NULL DEFAULT 0,
  entitlement_days numeric NOT NULL DEFAULT 0,
  used_days numeric NOT NULL DEFAULT 0,
  carried_forward_days numeric NOT NULL DEFAULT 0,
  remaining_days numeric NOT NULL DEFAULT 0,
  daily_wage numeric NOT NULL DEFAULT 0,
  compensation_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  legal_basis text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_annual_leave_pkey PRIMARY KEY (id),
  CONSTRAINT case_annual_leave_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_compensation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  claim_requested text NOT NULL DEFAULT 'yes'::text,
  compensation_type text,
  compensation_label text,
  legal_basis text,
  legal_reference text,
  contract_type text,
  termination_reason text,
  notice_status text NOT NULL DEFAULT 'no'::text,
  notice_required boolean NOT NULL DEFAULT false,
  notice_period_days integer,
  notice_actual_days integer,
  notice_shortfall_days integer,
  notice_compensation numeric NOT NULL DEFAULT 0,
  approved_wage numeric NOT NULL DEFAULT 0,
  service_years numeric NOT NULL DEFAULT 0,
  remaining_contract_months numeric,
  base_compensation numeric NOT NULL DEFAULT 0,
  final_compensation numeric NOT NULL DEFAULT 0,
  has_agreement_clause boolean NOT NULL DEFAULT false,
  agreement_amount numeric,
  agreement_method text,
  agreement_conflicts_law boolean NOT NULL DEFAULT false,
  payment_status text NOT NULL DEFAULT 'not_paid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  payment_date date,
  payment_method text,
  proof_file text,
  court_judgment_reference text,
  excluded_from_claim boolean NOT NULL DEFAULT false,
  legal_rule_version text,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  analysis jsonb,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_compensation_pkey PRIMARY KEY (id),
  CONSTRAINT case_compensation_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_sick_leave_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  has_sick_leave boolean NOT NULL DEFAULT false,
  ended_during_sick_leave boolean NOT NULL DEFAULT false,
  wage_changed boolean NOT NULL DEFAULT false,
  wage_basis text NOT NULL DEFAULT 'last_actual_wage'::text,
  leaves_count integer NOT NULL DEFAULT 0,
  total_days numeric NOT NULL DEFAULT 0,
  total_due numeric NOT NULL DEFAULT 0,
  total_paid numeric NOT NULL DEFAULT 0,
  excluded_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  daily_wage numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_sick_leave_summary_pkey PRIMARY KEY (id),
  CONSTRAINT case_sick_leave_summary_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_leave_carryover (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  from_year integer,
  days numeric NOT NULL DEFAULT 0,
  reason text,
  is_legal boolean NOT NULL DEFAULT true,
  proof_file text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_leave_carryover_pkey PRIMARY KEY (id),
  CONSTRAINT case_leave_carryover_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_salaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  basic_salary numeric NOT NULL DEFAULT 0,
  housing_allowance numeric NOT NULL DEFAULT 0,
  transport_allowance numeric NOT NULL DEFAULT 0,
  communication_allowance numeric NOT NULL DEFAULT 0,
  work_nature_allowance numeric NOT NULL DEFAULT 0,
  risk_allowance numeric NOT NULL DEFAULT 0,
  delegation_allowance numeric NOT NULL DEFAULT 0,
  other_allowances numeric NOT NULL DEFAULT 0,
  fixed_commission numeric NOT NULL DEFAULT 0,
  fixed_bonus numeric NOT NULL DEFAULT 0,
  other_benefits numeric NOT NULL DEFAULT 0,
  actual_salary numeric NOT NULL DEFAULT 0,
  daily_salary numeric NOT NULL DEFAULT 0,
  hourly_salary numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_salaries_pkey PRIMARY KEY (id),
  CONSTRAINT case_salaries_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_nursing_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  delivery_date date,
  return_to_work_date date,
  nursing_start_date date,
  nursing_end_date date,
  daily_working_hours numeric NOT NULL DEFAULT 8,
  daily_reduction_hours numeric NOT NULL DEFAULT 1,
  total_eligible_days numeric NOT NULL DEFAULT 0,
  total_reduction_hours numeric NOT NULL DEFAULT 0,
  paid boolean NOT NULL DEFAULT true,
  applied_rule jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_nursing_hours_pkey PRIMARY KEY (id),
  CONSTRAINT case_nursing_hours_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_leave_settlement (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  has_leave_claim boolean NOT NULL DEFAULT false,
  has_carryover boolean NOT NULL DEFAULT false,
  still_employed boolean NOT NULL DEFAULT false,
  wage_changed boolean NOT NULL DEFAULT false,
  wage_basis text NOT NULL DEFAULT 'last_actual_wage'::text,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  compensation_amount numeric NOT NULL DEFAULT 0,
  daily_wage numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  payment_date date,
  payment_method text,
  proof_type text,
  proof_file text,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_leave_settlement_pkey PRIMARY KEY (id),
  CONSTRAINT case_leave_settlement_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_holiday_work (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  holiday_name text,
  holiday_date date,
  end_date date,
  days numeric NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0,
  compensated boolean NOT NULL DEFAULT false,
  notes text,
  amount numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_holiday_work_pkey PRIMARY KEY (id),
  CONSTRAINT case_holiday_work_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_unpaid_salaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  month integer,
  year integer,
  due_date date,
  salary_type text NOT NULL DEFAULT 'monthly_salary'::text,
  amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  payment_date date,
  payment_method text,
  proof_type text,
  proof_file text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_unpaid_salaries_pkey PRIMARY KEY (id),
  CONSTRAINT case_unpaid_salaries_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  contract_number text NOT NULL,
  contract_name text,
  start_date date NOT NULL,
  end_date date,
  joining_date date,
  contract_type text NOT NULL DEFAULT 'fixed_term'::text,
  is_qiwa_documented boolean NOT NULL DEFAULT false,
  qiwa_contract_number text,
  renewed boolean NOT NULL DEFAULT false,
  renew_count integer NOT NULL DEFAULT 0,
  renew_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  ended boolean NOT NULL DEFAULT false,
  end_reason text,
  actual_end_date date,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT case_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT case_contracts_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_working_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  daily_hours numeric NOT NULL DEFAULT 8,
  weekly_days integer NOT NULL DEFAULT 6,
  shift_type text NOT NULL DEFAULT 'morning'::text,
  fingerprint_system boolean NOT NULL DEFAULT false,
  attendance_system boolean NOT NULL DEFAULT false,
  has_overtime boolean NOT NULL DEFAULT false,
  overtime_entry_mode text NOT NULL DEFAULT 'total'::text,
  overtime_total_hours numeric NOT NULL DEFAULT 0,
  has_weekend_work boolean NOT NULL DEFAULT false,
  has_holiday_work boolean NOT NULL DEFAULT false,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_working_hours_pkey PRIMARY KEY (id),
  CONSTRAINT case_working_hours_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_weekend_work (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  start_date date,
  end_date date,
  days numeric NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0,
  notes text,
  amount numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_weekend_work_pkey PRIMARY KEY (id),
  CONSTRAINT case_weekend_work_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_eosb (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  eligible boolean NOT NULL DEFAULT true,
  ineligibility_reason text,
  service_start_date date,
  service_end_date date,
  total_service_years integer NOT NULL DEFAULT 0,
  total_service_months integer NOT NULL DEFAULT 0,
  total_service_days integer NOT NULL DEFAULT 0,
  service_fraction_years numeric NOT NULL DEFAULT 0,
  last_approved_wage numeric NOT NULL DEFAULT 0,
  wage_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  contract_type text,
  termination_reason text,
  base_gratuity_amount numeric NOT NULL DEFAULT 0,
  eligibility_percentage numeric NOT NULL DEFAULT 0,
  final_gratuity_amount numeric NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'not_paid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  payment_date date,
  payment_method text,
  proof_file text,
  has_settlement boolean NOT NULL DEFAULT false,
  has_court_ruling boolean NOT NULL DEFAULT false,
  has_better_agreement boolean NOT NULL DEFAULT false,
  agreement_amount numeric,
  exceptions_notes text,
  legal_rule_version text,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_eosb_pkey PRIMARY KEY (id),
  CONSTRAINT case_eosb_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_report_sections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  section_key text NOT NULL,
  section_name text NOT NULL,
  section_order integer NOT NULL DEFAULT 0,
  included boolean NOT NULL DEFAULT true,
  visibility text NOT NULL DEFAULT 'all'::text,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_report_sections_pkey PRIMARY KEY (id),
  CONSTRAINT case_report_sections_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.case_final_reports(id)
);
CREATE TABLE public.admin_role_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  organization_id uuid,
  branch_id uuid,
  status text NOT NULL DEFAULT 'active'::text,
  mfa_enabled boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_role_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT admin_role_assignments_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.admin_roles(id),
  CONSTRAINT admin_role_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT admin_role_assignments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.api_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  api_key_id uuid,
  endpoint text NOT NULL,
  method text NOT NULL DEFAULT 'GET'::text,
  status_code integer,
  response_ms integer,
  ip_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT api_usage_logs_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id)
);
CREATE TABLE public.legal_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL,
  system_id uuid,
  rule_code text NOT NULL,
  rule_name text NOT NULL,
  rule_type text NOT NULL DEFAULT 'calculation'::text,
  claim_type text,
  sector text,
  worker_type text,
  contract_type text,
  priority integer NOT NULL DEFAULT 100,
  specificity integer NOT NULL DEFAULT 0,
  formula_id uuid,
  article_id uuid,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  description text,
  version text NOT NULL DEFAULT '1.0'::text,
  effective_date date NOT NULL DEFAULT CURRENT_DATE,
  expiry_date date,
  status text NOT NULL DEFAULT 'draft'::text,
  supersedes_id uuid,
  published_at timestamp with time zone,
  scheduled_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_rules_pkey PRIMARY KEY (id),
  CONSTRAINT legal_rules_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.legal_systems(id),
  CONSTRAINT legal_rules_formula_id_fkey FOREIGN KEY (formula_id) REFERENCES public.rule_formulas(id),
  CONSTRAINT legal_rules_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.legal_articles(id),
  CONSTRAINT legal_rules_supersedes_fk FOREIGN KEY (supersedes_id) REFERENCES public.legal_rules(id)
);
CREATE TABLE public.case_settlement_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  settlement_id uuid,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  right_type text NOT NULL,
  right_label text,
  related_module text,
  amount_due numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'SAR'::text,
  exchange_rate numeric,
  converted_amount numeric,
  payment_date date,
  payment_method text,
  proof_file text,
  match_status text NOT NULL DEFAULT 'needs_review'::text,
  mentioned_in_settlement boolean NOT NULL DEFAULT false,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_settlement_payments_pkey PRIMARY KEY (id),
  CONSTRAINT case_settlement_payments_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id),
  CONSTRAINT case_settlement_payments_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES public.case_final_settlement(id)
);
CREATE TABLE public.case_termination_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  termination_id uuid,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  doc_type text NOT NULL DEFAULT 'other'::text,
  doc_date date,
  file_path text,
  issuer text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_termination_documents_pkey PRIMARY KEY (id),
  CONSTRAINT case_termination_documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id),
  CONSTRAINT case_termination_documents_termination_id_fkey FOREIGN KEY (termination_id) REFERENCES public.case_termination(id)
);
CREATE TABLE public.case_social_insurance_monthly (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  insurance_id uuid,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  contribution_month integer NOT NULL DEFAULT 1,
  contribution_year integer NOT NULL DEFAULT 2024,
  period_key text NOT NULL DEFAULT ''::text,
  actual_wage numeric NOT NULL DEFAULT 0,
  insurable_wage numeric NOT NULL DEFAULT 0,
  registered_wage numeric NOT NULL DEFAULT 0,
  employee_rate numeric NOT NULL DEFAULT 0,
  employer_rate numeric NOT NULL DEFAULT 0,
  employee_contribution numeric NOT NULL DEFAULT 0,
  employer_contribution numeric NOT NULL DEFAULT 0,
  total_contribution numeric NOT NULL DEFAULT 0,
  registration_state text NOT NULL DEFAULT 'registered'::text,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  difference_amount numeric NOT NULL DEFAULT 0,
  payment_date date,
  payment_reference text,
  payment_entity text,
  payment_proof_type text,
  payment_proof_file text,
  currency text NOT NULL DEFAULT 'SAR'::text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_social_insurance_monthly_pkey PRIMARY KEY (id),
  CONSTRAINT case_social_insurance_monthly_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id),
  CONSTRAINT case_social_insurance_monthly_insurance_id_fkey FOREIGN KEY (insurance_id) REFERENCES public.case_social_insurance(id)
);
CREATE TABLE public.contract_trial_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL UNIQUE,
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  has_trial_period boolean NOT NULL DEFAULT false,
  trial_start_date date,
  trial_duration_days integer,
  trial_end_date date,
  is_extended boolean NOT NULL DEFAULT false,
  extension_duration_days integer,
  extension_reason text,
  extension_start_date date,
  extension_end_date date,
  termination_right text,
  ended_during_trial boolean NOT NULL DEFAULT false,
  who_terminated text,
  re_trial_analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contract_trial_periods_pkey PRIMARY KEY (id),
  CONSTRAINT contract_trial_periods_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.case_contracts(id),
  CONSTRAINT contract_trial_periods_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id)
);
CREATE TABLE public.case_sick_leaves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  contract_id uuid,
  start_date date,
  end_date date,
  total_days numeric NOT NULL DEFAULT 0,
  leave_kind text NOT NULL DEFAULT 'sick'::text,
  illness_reason text,
  medical_provider text,
  medical_report_number text,
  has_medical_report boolean NOT NULL DEFAULT false,
  medical_report_type text,
  medical_report_file text,
  daily_wage numeric NOT NULL DEFAULT 0,
  compensation_rate numeric NOT NULL DEFAULT 0,
  compensation_amount numeric NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid'::text,
  paid_amount numeric NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL DEFAULT 0,
  payment_method text,
  payment_date date,
  proof_type text,
  proof_file text,
  currency text NOT NULL DEFAULT 'SAR'::text,
  stages jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT case_sick_leaves_pkey PRIMARY KEY (id),
  CONSTRAINT case_sick_leaves_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.case_drafts(id),
  CONSTRAINT case_sick_leaves_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.case_contracts(id)
);
CREATE TABLE public.rule_test_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rule_id uuid,
  rule_code text,
  run_type text NOT NULL DEFAULT 'sandbox'::text,
  input_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb,
  previous_result jsonb,
  diff jsonb,
  passed boolean,
  duration_ms integer,
  run_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rule_test_runs_pkey PRIMARY KEY (id),
  CONSTRAINT rule_test_runs_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.legal_rules(id)
);
CREATE TABLE public.rule_exceptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL,
  rule_id uuid,
  exception_code text NOT NULL,
  exception_name text NOT NULL,
  category text NOT NULL DEFAULT 'special_category'::text,
  applies_to jsonb NOT NULL DEFAULT '{}'::jsonb,
  effect jsonb NOT NULL DEFAULT '{}'::jsonb,
  article_id uuid,
  priority integer NOT NULL DEFAULT 50,
  description text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rule_exceptions_pkey PRIMARY KEY (id),
  CONSTRAINT rule_exceptions_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.legal_rules(id),
  CONSTRAINT rule_exceptions_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.legal_articles(id)
);