/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DocumentSearchRouteImport } from './routes/document-search'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LawyerRegisterRouteImport } from './routes/lawyer-register'
import { Route as LawyersRouteImport } from './routes/lawyers'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PdfPreviewRouteImport } from './routes/pdf-preview'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SelectCountryRouteImport } from './routes/select-country'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedCalculationsRouteImport } from './routes/_authenticated/calculations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLawyerDashboardRouteImport } from './routes/_authenticated/lawyer-dashboard'
import { Route as AuthenticatedMySubscriptionRouteImport } from './routes/_authenticated/my-subscription'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedSubscriptionHistoryRouteImport } from './routes/_authenticated/subscription-history'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as LawyersSlugRouteImport } from './routes/lawyers.$slug'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedSaAnnualLeaveRouteImport } from './routes/_authenticated/sa/annual-leave'
import { Route as AuthenticatedSaCalculationEngineRouteImport } from './routes/_authenticated/sa/calculation-engine'
import { Route as AuthenticatedSaCalculatorRouteImport } from './routes/_authenticated/sa/calculator'
import { Route as AuthenticatedSaCaseInfoRouteImport } from './routes/_authenticated/sa/case-info'
import { Route as AuthenticatedSaCompensationRouteImport } from './routes/_authenticated/sa/compensation'
import { Route as AuthenticatedSaContractsRouteImport } from './routes/_authenticated/sa/contracts'
import { Route as AuthenticatedSaEosbRouteImport } from './routes/_authenticated/sa/eosb'
import { Route as AuthenticatedSaFinalReportRouteImport } from './routes/_authenticated/sa/final-report'
import { Route as AuthenticatedSaFinalSettlementRouteImport } from './routes/_authenticated/sa/final-settlement'
import { Route as AuthenticatedSaMaternityRouteImport } from './routes/_authenticated/sa/maternity'
import { Route as AuthenticatedSaSalaryRouteImport } from './routes/_authenticated/sa/salary'
import { Route as AuthenticatedSaSickLeaveRouteImport } from './routes/_authenticated/sa/sick-leave'
import { Route as AuthenticatedSaSocialInsuranceRouteImport } from './routes/_authenticated/sa/social-insurance'
import { Route as AuthenticatedSaTerminationRouteImport } from './routes/_authenticated/sa/termination'
import { Route as AuthenticatedSaTrialPeriodsRouteImport } from './routes/_authenticated/sa/trial-periods'
import { Route as AuthenticatedSaUnpaidSalariesRouteImport } from './routes/_authenticated/sa/unpaid-salaries'
import { Route as AuthenticatedSaWorkingHoursRouteImport } from './routes/_authenticated/sa/working-hours'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.admin-users'
import { Route as AuthenticatedAdminAdminAdsRouteImport } from './routes/_authenticated/_admin/admin.ads'
import { Route as AuthenticatedAdminAdminAiMonitoringRouteImport } from './routes/_authenticated/_admin/admin.ai-monitoring'
import { Route as AuthenticatedAdminAdminAnalyticsRouteImport } from './routes/_authenticated/_admin/admin.analytics'
import { Route as AuthenticatedAdminAdminApiRouteImport } from './routes/_authenticated/_admin/admin.api'
import { Route as AuthenticatedAdminAdminAuditRouteImport } from './routes/_authenticated/_admin/admin.audit'
import { Route as AuthenticatedAdminAdminBackupsRouteImport } from './routes/_authenticated/_admin/admin.backups'
import { Route as AuthenticatedAdminAdminBillingRouteImport } from './routes/_authenticated/_admin/admin.billing'
import { Route as AuthenticatedAdminAdminCalculationAuditRouteImport } from './routes/_authenticated/_admin/admin.calculation-audit'
import { Route as AuthenticatedAdminAdminCasesRouteImport } from './routes/_authenticated/_admin/admin.cases'
import { Route as AuthenticatedAdminAdminCountriesRouteImport } from './routes/_authenticated/_admin/admin.countries'
import { Route as AuthenticatedAdminAdminFeaturesRouteImport } from './routes/_authenticated/_admin/admin.features'
import { Route as AuthenticatedAdminAdminKnowledgeRouteImport } from './routes/_authenticated/_admin/admin.knowledge'
import { Route as AuthenticatedAdminAdminLawyersRouteImport } from './routes/_authenticated/_admin/admin.lawyers'
import { Route as AuthenticatedAdminAdminLegalContentRouteImport } from './routes/_authenticated/_admin/admin.legal-content'
import { Route as AuthenticatedAdminAdminLegalEngineRouteImport } from './routes/_authenticated/_admin/admin.legal-engine'
import { Route as AuthenticatedAdminAdminLegalReferencesRouteImport } from './routes/_authenticated/_admin/admin.legal-references'
import { Route as AuthenticatedAdminAdminLegalRulesRouteImport } from './routes/_authenticated/_admin/admin.legal-rules'
import { Route as AuthenticatedAdminAdminNotificationsRouteImport } from './routes/_authenticated/_admin/admin.notifications'
import { Route as AuthenticatedAdminAdminOrganizationsRouteImport } from './routes/_authenticated/_admin/admin.organizations'
import { Route as AuthenticatedAdminAdminOverviewRouteImport } from './routes/_authenticated/_admin/admin.overview'
import { Route as AuthenticatedAdminAdminPaymentsRouteImport } from './routes/_authenticated/_admin/admin.payments'
import { Route as AuthenticatedAdminAdminPermissionsRouteImport } from './routes/_authenticated/_admin/admin.permissions'
import { Route as AuthenticatedAdminAdminReferralsRouteImport } from './routes/_authenticated/_admin/admin.referrals'
import { Route as AuthenticatedAdminAdminReportTemplateRouteImport } from './routes/_authenticated/_admin/admin.report-template'
import { Route as AuthenticatedAdminAdminReportsCenterRouteImport } from './routes/_authenticated/_admin/admin.reports-center'
import { Route as AuthenticatedAdminAdminReviewsRouteImport } from './routes/_authenticated/_admin/admin.reviews'
import { Route as AuthenticatedAdminAdminRolesRouteImport } from './routes/_authenticated/_admin/admin.roles'
import { Route as AuthenticatedAdminAdminSaReportsRouteImport } from './routes/_authenticated/_admin/admin.sa-reports'
import { Route as AuthenticatedAdminAdminSecurityRouteImport } from './routes/_authenticated/_admin/admin.security'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated/_admin/admin.settings'
import { Route as AuthenticatedAdminAdminSubscriptionsRouteImport } from './routes/_authenticated/_admin/admin.subscriptions'
import { Route as AuthenticatedAdminAdminSystemRouteImport } from './routes/_authenticated/_admin/admin.system'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as ApiPublicRulesV1RouteImport } from './routes/api/public/rules.v1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentSearchRoute = DocumentSearchRouteImport.update({
  id: '/document-search',
  path: '/document-search',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRegisterRoute = LawyerRegisterRouteImport.update({
  id: '/lawyer-register',
  path: '/lawyer-register',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersRoute = LawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfPreviewRoute = PdfPreviewRouteImport.update({
  id: '/pdf-preview',
  path: '/pdf-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectCountryRoute = SelectCountryRouteImport.update({
  id: '/select-country',
  path: '/select-country',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculationsRoute =
  AuthenticatedCalculationsRouteImport.update({
    id: '/calculations',
    path: '/calculations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLawyerDashboardRoute =
  AuthenticatedLawyerDashboardRouteImport.update({
    id: '/lawyer-dashboard',
    path: '/lawyer-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMySubscriptionRoute =
  AuthenticatedMySubscriptionRouteImport.update({
    id: '/my-subscription',
    path: '/my-subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionHistoryRoute =
  AuthenticatedSubscriptionHistoryRouteImport.update({
    id: '/subscription-history',
    path: '/subscription-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const LawyersSlugRoute = LawyersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LawyersRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSaAnnualLeaveRoute =
  AuthenticatedSaAnnualLeaveRouteImport.update({
    id: '/sa/annual-leave',
    path: '/sa/annual-leave',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaCalculationEngineRoute =
  AuthenticatedSaCalculationEngineRouteImport.update({
    id: '/sa/calculation-engine',
    path: '/sa/calculation-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaCalculatorRoute =
  AuthenticatedSaCalculatorRouteImport.update({
    id: '/sa/calculator',
    path: '/sa/calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaCaseInfoRoute = AuthenticatedSaCaseInfoRouteImport.update({
  id: '/sa/case-info',
  path: '/sa/case-info',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaCompensationRoute =
  AuthenticatedSaCompensationRouteImport.update({
    id: '/sa/compensation',
    path: '/sa/compensation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaContractsRoute =
  AuthenticatedSaContractsRouteImport.update({
    id: '/sa/contracts',
    path: '/sa/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaEosbRoute = AuthenticatedSaEosbRouteImport.update({
  id: '/sa/eosb',
  path: '/sa/eosb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaFinalReportRoute =
  AuthenticatedSaFinalReportRouteImport.update({
    id: '/sa/final-report',
    path: '/sa/final-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaFinalSettlementRoute =
  AuthenticatedSaFinalSettlementRouteImport.update({
    id: '/sa/final-settlement',
    path: '/sa/final-settlement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaMaternityRoute =
  AuthenticatedSaMaternityRouteImport.update({
    id: '/sa/maternity',
    path: '/sa/maternity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaSalaryRoute = AuthenticatedSaSalaryRouteImport.update({
  id: '/sa/salary',
  path: '/sa/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaSickLeaveRoute =
  AuthenticatedSaSickLeaveRouteImport.update({
    id: '/sa/sick-leave',
    path: '/sa/sick-leave',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaSocialInsuranceRoute =
  AuthenticatedSaSocialInsuranceRouteImport.update({
    id: '/sa/social-insurance',
    path: '/sa/social-insurance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaTerminationRoute =
  AuthenticatedSaTerminationRouteImport.update({
    id: '/sa/termination',
    path: '/sa/termination',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaTrialPeriodsRoute =
  AuthenticatedSaTrialPeriodsRouteImport.update({
    id: '/sa/trial-periods',
    path: '/sa/trial-periods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaUnpaidSalariesRoute =
  AuthenticatedSaUnpaidSalariesRouteImport.update({
    id: '/sa/unpaid-salaries',
    path: '/sa/unpaid-salaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaWorkingHoursRoute =
  AuthenticatedSaWorkingHoursRouteImport.update({
    id: '/sa/working-hours',
    path: '/sa/working-hours',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminAdminUsersRoute =
  AuthenticatedAdminAdminAdminUsersRouteImport.update({
    id: '/admin-users',
    path: '/admin-users',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminAdsRoute =
  AuthenticatedAdminAdminAdsRouteImport.update({
    id: '/ads',
    path: '/ads',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiMonitoringRoute =
  AuthenticatedAdminAdminAiMonitoringRouteImport.update({
    id: '/ai-monitoring',
    path: '/ai-monitoring',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnalyticsRoute =
  AuthenticatedAdminAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminApiRoute =
  AuthenticatedAdminAdminApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminAuditRoute =
  AuthenticatedAdminAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminBackupsRoute =
  AuthenticatedAdminAdminBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminBillingRoute =
  AuthenticatedAdminAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminCalculationAuditRoute =
  AuthenticatedAdminAdminCalculationAuditRouteImport.update({
    id: '/calculation-audit',
    path: '/calculation-audit',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminCasesRoute =
  AuthenticatedAdminAdminCasesRouteImport.update({
    id: '/cases',
    path: '/cases',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminCountriesRoute =
  AuthenticatedAdminAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminFeaturesRoute =
  AuthenticatedAdminAdminFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminKnowledgeRoute =
  AuthenticatedAdminAdminKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminLawyersRoute =
  AuthenticatedAdminAdminLawyersRouteImport.update({
    id: '/lawyers',
    path: '/lawyers',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminLegalContentRoute =
  AuthenticatedAdminAdminLegalContentRouteImport.update({
    id: '/legal-content',
    path: '/legal-content',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminLegalEngineRoute =
  AuthenticatedAdminAdminLegalEngineRouteImport.update({
    id: '/legal-engine',
    path: '/legal-engine',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminLegalReferencesRoute =
  AuthenticatedAdminAdminLegalReferencesRouteImport.update({
    id: '/legal-references',
    path: '/legal-references',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminLegalRulesRoute =
  AuthenticatedAdminAdminLegalRulesRouteImport.update({
    id: '/legal-rules',
    path: '/legal-rules',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminNotificationsRoute =
  AuthenticatedAdminAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrganizationsRoute =
  AuthenticatedAdminAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminOverviewRoute =
  AuthenticatedAdminAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminPaymentsRoute =
  AuthenticatedAdminAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminPermissionsRoute =
  AuthenticatedAdminAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminReferralsRoute =
  AuthenticatedAdminAdminReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminReportTemplateRoute =
  AuthenticatedAdminAdminReportTemplateRouteImport.update({
    id: '/report-template',
    path: '/report-template',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminReportsCenterRoute =
  AuthenticatedAdminAdminReportsCenterRouteImport.update({
    id: '/reports-center',
    path: '/reports-center',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminReviewsRoute =
  AuthenticatedAdminAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminRolesRoute =
  AuthenticatedAdminAdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminSaReportsRoute =
  AuthenticatedAdminAdminSaReportsRouteImport.update({
    id: '/sa-reports',
    path: '/sa-reports',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminSecurityRoute =
  AuthenticatedAdminAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminSubscriptionsRoute =
  AuthenticatedAdminAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminSystemRoute =
  AuthenticatedAdminAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const ApiPublicRulesV1Route = ApiPublicRulesV1RouteImport.update({
  id: '/api/public/rules/v1',
  path: '/api/public/rules/v1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-search': typeof DocumentSearchRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lawyer-register': typeof LawyerRegisterRoute
  '/lawyers': typeof LawyersRouteWithChildren
  '/payment-methods': typeof PaymentMethodsRoute
  '/pdf-preview': typeof PdfPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-country': typeof SelectCountryRoute
  '/subscribe': typeof SubscribeRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/calculations': typeof AuthenticatedCalculationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lawyer-dashboard': typeof AuthenticatedLawyerDashboardRoute
  '/my-subscription': typeof AuthenticatedMySubscriptionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/subscription-history': typeof AuthenticatedSubscriptionHistoryRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/lawyers/$slug': typeof LawyersSlugRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/sa/annual-leave': typeof AuthenticatedSaAnnualLeaveRoute
  '/sa/calculation-engine': typeof AuthenticatedSaCalculationEngineRoute
  '/sa/calculator': typeof AuthenticatedSaCalculatorRoute
  '/sa/case-info': typeof AuthenticatedSaCaseInfoRoute
  '/sa/compensation': typeof AuthenticatedSaCompensationRoute
  '/sa/contracts': typeof AuthenticatedSaContractsRoute
  '/sa/eosb': typeof AuthenticatedSaEosbRoute
  '/sa/final-report': typeof AuthenticatedSaFinalReportRoute
  '/sa/final-settlement': typeof AuthenticatedSaFinalSettlementRoute
  '/sa/maternity': typeof AuthenticatedSaMaternityRoute
  '/sa/salary': typeof AuthenticatedSaSalaryRoute
  '/sa/sick-leave': typeof AuthenticatedSaSickLeaveRoute
  '/sa/social-insurance': typeof AuthenticatedSaSocialInsuranceRoute
  '/sa/termination': typeof AuthenticatedSaTerminationRoute
  '/sa/trial-periods': typeof AuthenticatedSaTrialPeriodsRoute
  '/sa/unpaid-salaries': typeof AuthenticatedSaUnpaidSalariesRoute
  '/sa/working-hours': typeof AuthenticatedSaWorkingHoursRoute
  '/admin/admin-users': typeof AuthenticatedAdminAdminAdminUsersRoute
  '/admin/ads': typeof AuthenticatedAdminAdminAdsRoute
  '/admin/ai-monitoring': typeof AuthenticatedAdminAdminAiMonitoringRoute
  '/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/admin/api': typeof AuthenticatedAdminAdminApiRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/backups': typeof AuthenticatedAdminAdminBackupsRoute
  '/admin/billing': typeof AuthenticatedAdminAdminBillingRoute
  '/admin/calculation-audit': typeof AuthenticatedAdminAdminCalculationAuditRoute
  '/admin/cases': typeof AuthenticatedAdminAdminCasesRoute
  '/admin/countries': typeof AuthenticatedAdminAdminCountriesRoute
  '/admin/features': typeof AuthenticatedAdminAdminFeaturesRoute
  '/admin/knowledge': typeof AuthenticatedAdminAdminKnowledgeRoute
  '/admin/lawyers': typeof AuthenticatedAdminAdminLawyersRoute
  '/admin/legal-content': typeof AuthenticatedAdminAdminLegalContentRoute
  '/admin/legal-engine': typeof AuthenticatedAdminAdminLegalEngineRoute
  '/admin/legal-references': typeof AuthenticatedAdminAdminLegalReferencesRoute
  '/admin/legal-rules': typeof AuthenticatedAdminAdminLegalRulesRoute
  '/admin/notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/admin/overview': typeof AuthenticatedAdminAdminOverviewRoute
  '/admin/payments': typeof AuthenticatedAdminAdminPaymentsRoute
  '/admin/permissions': typeof AuthenticatedAdminAdminPermissionsRoute
  '/admin/referrals': typeof AuthenticatedAdminAdminReferralsRoute
  '/admin/report-template': typeof AuthenticatedAdminAdminReportTemplateRoute
  '/admin/reports-center': typeof AuthenticatedAdminAdminReportsCenterRoute
  '/admin/reviews': typeof AuthenticatedAdminAdminReviewsRoute
  '/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/admin/sa-reports': typeof AuthenticatedAdminAdminSaReportsRoute
  '/admin/security': typeof AuthenticatedAdminAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/admin/system': typeof AuthenticatedAdminAdminSystemRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/api/public/rules/v1': typeof ApiPublicRulesV1Route
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-search': typeof DocumentSearchRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lawyer-register': typeof LawyerRegisterRoute
  '/lawyers': typeof LawyersRouteWithChildren
  '/payment-methods': typeof PaymentMethodsRoute
  '/pdf-preview': typeof PdfPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-country': typeof SelectCountryRoute
  '/subscribe': typeof SubscribeRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/calculations': typeof AuthenticatedCalculationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lawyer-dashboard': typeof AuthenticatedLawyerDashboardRoute
  '/my-subscription': typeof AuthenticatedMySubscriptionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/subscription-history': typeof AuthenticatedSubscriptionHistoryRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/lawyers/$slug': typeof LawyersSlugRoute
  '/sa/annual-leave': typeof AuthenticatedSaAnnualLeaveRoute
  '/sa/calculation-engine': typeof AuthenticatedSaCalculationEngineRoute
  '/sa/calculator': typeof AuthenticatedSaCalculatorRoute
  '/sa/case-info': typeof AuthenticatedSaCaseInfoRoute
  '/sa/compensation': typeof AuthenticatedSaCompensationRoute
  '/sa/contracts': typeof AuthenticatedSaContractsRoute
  '/sa/eosb': typeof AuthenticatedSaEosbRoute
  '/sa/final-report': typeof AuthenticatedSaFinalReportRoute
  '/sa/final-settlement': typeof AuthenticatedSaFinalSettlementRoute
  '/sa/maternity': typeof AuthenticatedSaMaternityRoute
  '/sa/salary': typeof AuthenticatedSaSalaryRoute
  '/sa/sick-leave': typeof AuthenticatedSaSickLeaveRoute
  '/sa/social-insurance': typeof AuthenticatedSaSocialInsuranceRoute
  '/sa/termination': typeof AuthenticatedSaTerminationRoute
  '/sa/trial-periods': typeof AuthenticatedSaTrialPeriodsRoute
  '/sa/unpaid-salaries': typeof AuthenticatedSaUnpaidSalariesRoute
  '/sa/working-hours': typeof AuthenticatedSaWorkingHoursRoute
  '/admin/admin-users': typeof AuthenticatedAdminAdminAdminUsersRoute
  '/admin/ads': typeof AuthenticatedAdminAdminAdsRoute
  '/admin/ai-monitoring': typeof AuthenticatedAdminAdminAiMonitoringRoute
  '/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/admin/api': typeof AuthenticatedAdminAdminApiRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/backups': typeof AuthenticatedAdminAdminBackupsRoute
  '/admin/billing': typeof AuthenticatedAdminAdminBillingRoute
  '/admin/calculation-audit': typeof AuthenticatedAdminAdminCalculationAuditRoute
  '/admin/cases': typeof AuthenticatedAdminAdminCasesRoute
  '/admin/countries': typeof AuthenticatedAdminAdminCountriesRoute
  '/admin/features': typeof AuthenticatedAdminAdminFeaturesRoute
  '/admin/knowledge': typeof AuthenticatedAdminAdminKnowledgeRoute
  '/admin/lawyers': typeof AuthenticatedAdminAdminLawyersRoute
  '/admin/legal-content': typeof AuthenticatedAdminAdminLegalContentRoute
  '/admin/legal-engine': typeof AuthenticatedAdminAdminLegalEngineRoute
  '/admin/legal-references': typeof AuthenticatedAdminAdminLegalReferencesRoute
  '/admin/legal-rules': typeof AuthenticatedAdminAdminLegalRulesRoute
  '/admin/notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/admin/overview': typeof AuthenticatedAdminAdminOverviewRoute
  '/admin/payments': typeof AuthenticatedAdminAdminPaymentsRoute
  '/admin/permissions': typeof AuthenticatedAdminAdminPermissionsRoute
  '/admin/referrals': typeof AuthenticatedAdminAdminReferralsRoute
  '/admin/report-template': typeof AuthenticatedAdminAdminReportTemplateRoute
  '/admin/reports-center': typeof AuthenticatedAdminAdminReportsCenterRoute
  '/admin/reviews': typeof AuthenticatedAdminAdminReviewsRoute
  '/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/admin/sa-reports': typeof AuthenticatedAdminAdminSaReportsRoute
  '/admin/security': typeof AuthenticatedAdminAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/admin/system': typeof AuthenticatedAdminAdminSystemRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/api/public/rules/v1': typeof ApiPublicRulesV1Route
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/document-search': typeof DocumentSearchRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/lawyer-register': typeof LawyerRegisterRoute
  '/lawyers': typeof LawyersRouteWithChildren
  '/payment-methods': typeof PaymentMethodsRoute
  '/pdf-preview': typeof PdfPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-country': typeof SelectCountryRoute
  '/subscribe': typeof SubscribeRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/calculations': typeof AuthenticatedCalculationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lawyer-dashboard': typeof AuthenticatedLawyerDashboardRoute
  '/_authenticated/my-subscription': typeof AuthenticatedMySubscriptionRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/subscription-history': typeof AuthenticatedSubscriptionHistoryRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/lawyers/$slug': typeof LawyersSlugRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/_authenticated/sa/annual-leave': typeof AuthenticatedSaAnnualLeaveRoute
  '/_authenticated/sa/calculation-engine': typeof AuthenticatedSaCalculationEngineRoute
  '/_authenticated/sa/calculator': typeof AuthenticatedSaCalculatorRoute
  '/_authenticated/sa/case-info': typeof AuthenticatedSaCaseInfoRoute
  '/_authenticated/sa/compensation': typeof AuthenticatedSaCompensationRoute
  '/_authenticated/sa/contracts': typeof AuthenticatedSaContractsRoute
  '/_authenticated/sa/eosb': typeof AuthenticatedSaEosbRoute
  '/_authenticated/sa/final-report': typeof AuthenticatedSaFinalReportRoute
  '/_authenticated/sa/final-settlement': typeof AuthenticatedSaFinalSettlementRoute
  '/_authenticated/sa/maternity': typeof AuthenticatedSaMaternityRoute
  '/_authenticated/sa/salary': typeof AuthenticatedSaSalaryRoute
  '/_authenticated/sa/sick-leave': typeof AuthenticatedSaSickLeaveRoute
  '/_authenticated/sa/social-insurance': typeof AuthenticatedSaSocialInsuranceRoute
  '/_authenticated/sa/termination': typeof AuthenticatedSaTerminationRoute
  '/_authenticated/sa/trial-periods': typeof AuthenticatedSaTrialPeriodsRoute
  '/_authenticated/sa/unpaid-salaries': typeof AuthenticatedSaUnpaidSalariesRoute
  '/_authenticated/sa/working-hours': typeof AuthenticatedSaWorkingHoursRoute
  '/_authenticated/_admin/admin/admin-users': typeof AuthenticatedAdminAdminAdminUsersRoute
  '/_authenticated/_admin/admin/ads': typeof AuthenticatedAdminAdminAdsRoute
  '/_authenticated/_admin/admin/ai-monitoring': typeof AuthenticatedAdminAdminAiMonitoringRoute
  '/_authenticated/_admin/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/_authenticated/_admin/admin/api': typeof AuthenticatedAdminAdminApiRoute
  '/_authenticated/_admin/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/_authenticated/_admin/admin/backups': typeof AuthenticatedAdminAdminBackupsRoute
  '/_authenticated/_admin/admin/billing': typeof AuthenticatedAdminAdminBillingRoute
  '/_authenticated/_admin/admin/calculation-audit': typeof AuthenticatedAdminAdminCalculationAuditRoute
  '/_authenticated/_admin/admin/cases': typeof AuthenticatedAdminAdminCasesRoute
  '/_authenticated/_admin/admin/countries': typeof AuthenticatedAdminAdminCountriesRoute
  '/_authenticated/_admin/admin/features': typeof AuthenticatedAdminAdminFeaturesRoute
  '/_authenticated/_admin/admin/knowledge': typeof AuthenticatedAdminAdminKnowledgeRoute
  '/_authenticated/_admin/admin/lawyers': typeof AuthenticatedAdminAdminLawyersRoute
  '/_authenticated/_admin/admin/legal-content': typeof AuthenticatedAdminAdminLegalContentRoute
  '/_authenticated/_admin/admin/legal-engine': typeof AuthenticatedAdminAdminLegalEngineRoute
  '/_authenticated/_admin/admin/legal-references': typeof AuthenticatedAdminAdminLegalReferencesRoute
  '/_authenticated/_admin/admin/legal-rules': typeof AuthenticatedAdminAdminLegalRulesRoute
  '/_authenticated/_admin/admin/notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/_authenticated/_admin/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/_authenticated/_admin/admin/overview': typeof AuthenticatedAdminAdminOverviewRoute
  '/_authenticated/_admin/admin/payments': typeof AuthenticatedAdminAdminPaymentsRoute
  '/_authenticated/_admin/admin/permissions': typeof AuthenticatedAdminAdminPermissionsRoute
  '/_authenticated/_admin/admin/referrals': typeof AuthenticatedAdminAdminReferralsRoute
  '/_authenticated/_admin/admin/report-template': typeof AuthenticatedAdminAdminReportTemplateRoute
  '/_authenticated/_admin/admin/reports-center': typeof AuthenticatedAdminAdminReportsCenterRoute
  '/_authenticated/_admin/admin/reviews': typeof AuthenticatedAdminAdminReviewsRoute
  '/_authenticated/_admin/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/_authenticated/_admin/admin/sa-reports': typeof AuthenticatedAdminAdminSaReportsRoute
  '/_authenticated/_admin/admin/security': typeof AuthenticatedAdminAdminSecurityRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/_authenticated/_admin/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/_authenticated/_admin/admin/system': typeof AuthenticatedAdminAdminSystemRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/api/public/rules/v1': typeof ApiPublicRulesV1Route
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/disclaimer'
    | '/document-search'
    | '/knowledge'
    | '/lawyer-register'
    | '/lawyers'
    | '/payment-methods'
    | '/pdf-preview'
    | '/privacy'
    | '/reset-password'
    | '/select-country'
    | '/subscribe'
    | '/support'
    | '/terms'
    | '/verify'
    | '/calculations'
    | '/dashboard'
    | '/lawyer-dashboard'
    | '/my-subscription'
    | '/profile'
    | '/referrals'
    | '/subscription-history'
    | '/admin/change-password'
    | '/admin/login'
    | '/api/health'
    | '/auth/callback'
    | '/knowledge/$slug'
    | '/lawyers/$slug'
    | '/admin'
    | '/sa/annual-leave'
    | '/sa/calculation-engine'
    | '/sa/calculator'
    | '/sa/case-info'
    | '/sa/compensation'
    | '/sa/contracts'
    | '/sa/eosb'
    | '/sa/final-report'
    | '/sa/final-settlement'
    | '/sa/maternity'
    | '/sa/salary'
    | '/sa/sick-leave'
    | '/sa/social-insurance'
    | '/sa/termination'
    | '/sa/trial-periods'
    | '/sa/unpaid-salaries'
    | '/sa/working-hours'
    | '/admin/admin-users'
    | '/admin/ads'
    | '/admin/ai-monitoring'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/billing'
    | '/admin/calculation-audit'
    | '/admin/cases'
    | '/admin/countries'
    | '/admin/features'
    | '/admin/knowledge'
    | '/admin/lawyers'
    | '/admin/legal-content'
    | '/admin/legal-engine'
    | '/admin/legal-references'
    | '/admin/legal-rules'
    | '/admin/notifications'
    | '/admin/organizations'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/referrals'
    | '/admin/report-template'
    | '/admin/reports-center'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/sa-reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/users'
    | '/api/public/rules/v1'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/disclaimer'
    | '/document-search'
    | '/knowledge'
    | '/lawyer-register'
    | '/lawyers'
    | '/payment-methods'
    | '/pdf-preview'
    | '/privacy'
    | '/reset-password'
    | '/select-country'
    | '/subscribe'
    | '/support'
    | '/terms'
    | '/verify'
    | '/calculations'
    | '/dashboard'
    | '/lawyer-dashboard'
    | '/my-subscription'
    | '/profile'
    | '/referrals'
    | '/subscription-history'
    | '/admin/change-password'
    | '/admin/login'
    | '/api/health'
    | '/auth/callback'
    | '/knowledge/$slug'
    | '/lawyers/$slug'
    | '/sa/annual-leave'
    | '/sa/calculation-engine'
    | '/sa/calculator'
    | '/sa/case-info'
    | '/sa/compensation'
    | '/sa/contracts'
    | '/sa/eosb'
    | '/sa/final-report'
    | '/sa/final-settlement'
    | '/sa/maternity'
    | '/sa/salary'
    | '/sa/sick-leave'
    | '/sa/social-insurance'
    | '/sa/termination'
    | '/sa/trial-periods'
    | '/sa/unpaid-salaries'
    | '/sa/working-hours'
    | '/admin/admin-users'
    | '/admin/ads'
    | '/admin/ai-monitoring'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/billing'
    | '/admin/calculation-audit'
    | '/admin/cases'
    | '/admin/countries'
    | '/admin/features'
    | '/admin/knowledge'
    | '/admin/lawyers'
    | '/admin/legal-content'
    | '/admin/legal-engine'
    | '/admin/legal-references'
    | '/admin/legal-rules'
    | '/admin/notifications'
    | '/admin/organizations'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/referrals'
    | '/admin/report-template'
    | '/admin/reports-center'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/sa-reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/users'
    | '/api/public/rules/v1'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculator'
    | '/disclaimer'
    | '/document-search'
    | '/knowledge'
    | '/lawyer-register'
    | '/lawyers'
    | '/payment-methods'
    | '/pdf-preview'
    | '/privacy'
    | '/reset-password'
    | '/select-country'
    | '/subscribe'
    | '/support'
    | '/terms'
    | '/verify'
    | '/_authenticated/_admin'
    | '/_authenticated/calculations'
    | '/_authenticated/dashboard'
    | '/_authenticated/lawyer-dashboard'
    | '/_authenticated/my-subscription'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/subscription-history'
    | '/admin/change-password'
    | '/admin/login'
    | '/api/health'
    | '/auth/callback'
    | '/knowledge/$slug'
    | '/lawyers/$slug'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/sa/annual-leave'
    | '/_authenticated/sa/calculation-engine'
    | '/_authenticated/sa/calculator'
    | '/_authenticated/sa/case-info'
    | '/_authenticated/sa/compensation'
    | '/_authenticated/sa/contracts'
    | '/_authenticated/sa/eosb'
    | '/_authenticated/sa/final-report'
    | '/_authenticated/sa/final-settlement'
    | '/_authenticated/sa/maternity'
    | '/_authenticated/sa/salary'
    | '/_authenticated/sa/sick-leave'
    | '/_authenticated/sa/social-insurance'
    | '/_authenticated/sa/termination'
    | '/_authenticated/sa/trial-periods'
    | '/_authenticated/sa/unpaid-salaries'
    | '/_authenticated/sa/working-hours'
    | '/_authenticated/_admin/admin/admin-users'
    | '/_authenticated/_admin/admin/ads'
    | '/_authenticated/_admin/admin/ai-monitoring'
    | '/_authenticated/_admin/admin/analytics'
    | '/_authenticated/_admin/admin/api'
    | '/_authenticated/_admin/admin/audit'
    | '/_authenticated/_admin/admin/backups'
    | '/_authenticated/_admin/admin/billing'
    | '/_authenticated/_admin/admin/calculation-audit'
    | '/_authenticated/_admin/admin/cases'
    | '/_authenticated/_admin/admin/countries'
    | '/_authenticated/_admin/admin/features'
    | '/_authenticated/_admin/admin/knowledge'
    | '/_authenticated/_admin/admin/lawyers'
    | '/_authenticated/_admin/admin/legal-content'
    | '/_authenticated/_admin/admin/legal-engine'
    | '/_authenticated/_admin/admin/legal-references'
    | '/_authenticated/_admin/admin/legal-rules'
    | '/_authenticated/_admin/admin/notifications'
    | '/_authenticated/_admin/admin/organizations'
    | '/_authenticated/_admin/admin/overview'
    | '/_authenticated/_admin/admin/payments'
    | '/_authenticated/_admin/admin/permissions'
    | '/_authenticated/_admin/admin/referrals'
    | '/_authenticated/_admin/admin/report-template'
    | '/_authenticated/_admin/admin/reports-center'
    | '/_authenticated/_admin/admin/reviews'
    | '/_authenticated/_admin/admin/roles'
    | '/_authenticated/_admin/admin/sa-reports'
    | '/_authenticated/_admin/admin/security'
    | '/_authenticated/_admin/admin/settings'
    | '/_authenticated/_admin/admin/subscriptions'
    | '/_authenticated/_admin/admin/system'
    | '/_authenticated/_admin/admin/users'
    | '/api/public/rules/v1'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DocumentSearchRoute: typeof DocumentSearchRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LawyerRegisterRoute: typeof LawyerRegisterRoute
  LawyersRoute: typeof LawyersRouteWithChildren
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PdfPreviewRoute: typeof PdfPreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectCountryRoute: typeof SelectCountryRoute
  SubscribeRoute: typeof SubscribeRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPublicRulesV1Route: typeof ApiPublicRulesV1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-search': {
      id: '/document-search'
      path: '/document-search'
      fullPath: '/document-search'
      preLoaderRoute: typeof DocumentSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-register': {
      id: '/lawyer-register'
      path: '/lawyer-register'
      fullPath: '/lawyer-register'
      preLoaderRoute: typeof LawyerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers': {
      id: '/lawyers'
      path: '/lawyers'
      fullPath: '/lawyers'
      preLoaderRoute: typeof LawyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-preview': {
      id: '/pdf-preview'
      path: '/pdf-preview'
      fullPath: '/pdf-preview'
      preLoaderRoute: typeof PdfPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-country': {
      id: '/select-country'
      path: '/select-country'
      fullPath: '/select-country'
      preLoaderRoute: typeof SelectCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculations': {
      id: '/_authenticated/calculations'
      path: '/calculations'
      fullPath: '/calculations'
      preLoaderRoute: typeof AuthenticatedCalculationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lawyer-dashboard': {
      id: '/_authenticated/lawyer-dashboard'
      path: '/lawyer-dashboard'
      fullPath: '/lawyer-dashboard'
      preLoaderRoute: typeof AuthenticatedLawyerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-subscription': {
      id: '/_authenticated/my-subscription'
      path: '/my-subscription'
      fullPath: '/my-subscription'
      preLoaderRoute: typeof AuthenticatedMySubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription-history': {
      id: '/_authenticated/subscription-history'
      path: '/subscription-history'
      fullPath: '/subscription-history'
      preLoaderRoute: typeof AuthenticatedSubscriptionHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/lawyers/$slug': {
      id: '/lawyers/$slug'
      path: '/$slug'
      fullPath: '/lawyers/$slug'
      preLoaderRoute: typeof LawyersSlugRouteImport
      parentRoute: typeof LawyersRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/sa/annual-leave': {
      id: '/_authenticated/sa/annual-leave'
      path: '/sa/annual-leave'
      fullPath: '/sa/annual-leave'
      preLoaderRoute: typeof AuthenticatedSaAnnualLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/calculation-engine': {
      id: '/_authenticated/sa/calculation-engine'
      path: '/sa/calculation-engine'
      fullPath: '/sa/calculation-engine'
      preLoaderRoute: typeof AuthenticatedSaCalculationEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/calculator': {
      id: '/_authenticated/sa/calculator'
      path: '/sa/calculator'
      fullPath: '/sa/calculator'
      preLoaderRoute: typeof AuthenticatedSaCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/case-info': {
      id: '/_authenticated/sa/case-info'
      path: '/sa/case-info'
      fullPath: '/sa/case-info'
      preLoaderRoute: typeof AuthenticatedSaCaseInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/compensation': {
      id: '/_authenticated/sa/compensation'
      path: '/sa/compensation'
      fullPath: '/sa/compensation'
      preLoaderRoute: typeof AuthenticatedSaCompensationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/contracts': {
      id: '/_authenticated/sa/contracts'
      path: '/sa/contracts'
      fullPath: '/sa/contracts'
      preLoaderRoute: typeof AuthenticatedSaContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/eosb': {
      id: '/_authenticated/sa/eosb'
      path: '/sa/eosb'
      fullPath: '/sa/eosb'
      preLoaderRoute: typeof AuthenticatedSaEosbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/final-report': {
      id: '/_authenticated/sa/final-report'
      path: '/sa/final-report'
      fullPath: '/sa/final-report'
      preLoaderRoute: typeof AuthenticatedSaFinalReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/final-settlement': {
      id: '/_authenticated/sa/final-settlement'
      path: '/sa/final-settlement'
      fullPath: '/sa/final-settlement'
      preLoaderRoute: typeof AuthenticatedSaFinalSettlementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/maternity': {
      id: '/_authenticated/sa/maternity'
      path: '/sa/maternity'
      fullPath: '/sa/maternity'
      preLoaderRoute: typeof AuthenticatedSaMaternityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/salary': {
      id: '/_authenticated/sa/salary'
      path: '/sa/salary'
      fullPath: '/sa/salary'
      preLoaderRoute: typeof AuthenticatedSaSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/sick-leave': {
      id: '/_authenticated/sa/sick-leave'
      path: '/sa/sick-leave'
      fullPath: '/sa/sick-leave'
      preLoaderRoute: typeof AuthenticatedSaSickLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/social-insurance': {
      id: '/_authenticated/sa/social-insurance'
      path: '/sa/social-insurance'
      fullPath: '/sa/social-insurance'
      preLoaderRoute: typeof AuthenticatedSaSocialInsuranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/termination': {
      id: '/_authenticated/sa/termination'
      path: '/sa/termination'
      fullPath: '/sa/termination'
      preLoaderRoute: typeof AuthenticatedSaTerminationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/trial-periods': {
      id: '/_authenticated/sa/trial-periods'
      path: '/sa/trial-periods'
      fullPath: '/sa/trial-periods'
      preLoaderRoute: typeof AuthenticatedSaTrialPeriodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/unpaid-salaries': {
      id: '/_authenticated/sa/unpaid-salaries'
      path: '/sa/unpaid-salaries'
      fullPath: '/sa/unpaid-salaries'
      preLoaderRoute: typeof AuthenticatedSaUnpaidSalariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa/working-hours': {
      id: '/_authenticated/sa/working-hours'
      path: '/sa/working-hours'
      fullPath: '/sa/working-hours'
      preLoaderRoute: typeof AuthenticatedSaWorkingHoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/admin-users': {
      id: '/_authenticated/_admin/admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin/admin-users'
      preLoaderRoute: typeof AuthenticatedAdminAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/ads': {
      id: '/_authenticated/_admin/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/ai-monitoring': {
      id: '/_authenticated/_admin/admin/ai-monitoring'
      path: '/ai-monitoring'
      fullPath: '/admin/ai-monitoring'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/analytics': {
      id: '/_authenticated/_admin/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/api': {
      id: '/_authenticated/_admin/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AuthenticatedAdminAdminApiRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/audit': {
      id: '/_authenticated/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/backups': {
      id: '/_authenticated/_admin/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AuthenticatedAdminAdminBackupsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/billing': {
      id: '/_authenticated/_admin/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/calculation-audit': {
      id: '/_authenticated/_admin/admin/calculation-audit'
      path: '/calculation-audit'
      fullPath: '/admin/calculation-audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminCalculationAuditRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/cases': {
      id: '/_authenticated/_admin/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AuthenticatedAdminAdminCasesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/countries': {
      id: '/_authenticated/_admin/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/features': {
      id: '/_authenticated/_admin/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AuthenticatedAdminAdminFeaturesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/knowledge': {
      id: '/_authenticated/_admin/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/lawyers': {
      id: '/_authenticated/_admin/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof AuthenticatedAdminAdminLawyersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/legal-content': {
      id: '/_authenticated/_admin/admin/legal-content'
      path: '/legal-content'
      fullPath: '/admin/legal-content'
      preLoaderRoute: typeof AuthenticatedAdminAdminLegalContentRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/legal-engine': {
      id: '/_authenticated/_admin/admin/legal-engine'
      path: '/legal-engine'
      fullPath: '/admin/legal-engine'
      preLoaderRoute: typeof AuthenticatedAdminAdminLegalEngineRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/legal-references': {
      id: '/_authenticated/_admin/admin/legal-references'
      path: '/legal-references'
      fullPath: '/admin/legal-references'
      preLoaderRoute: typeof AuthenticatedAdminAdminLegalReferencesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/legal-rules': {
      id: '/_authenticated/_admin/admin/legal-rules'
      path: '/legal-rules'
      fullPath: '/admin/legal-rules'
      preLoaderRoute: typeof AuthenticatedAdminAdminLegalRulesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/notifications': {
      id: '/_authenticated/_admin/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/organizations': {
      id: '/_authenticated/_admin/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/overview': {
      id: '/_authenticated/_admin/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/payments': {
      id: '/_authenticated/_admin/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/permissions': {
      id: '/_authenticated/_admin/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/referrals': {
      id: '/_authenticated/_admin/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/report-template': {
      id: '/_authenticated/_admin/admin/report-template'
      path: '/report-template'
      fullPath: '/admin/report-template'
      preLoaderRoute: typeof AuthenticatedAdminAdminReportTemplateRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/reports-center': {
      id: '/_authenticated/_admin/admin/reports-center'
      path: '/reports-center'
      fullPath: '/admin/reports-center'
      preLoaderRoute: typeof AuthenticatedAdminAdminReportsCenterRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/reviews': {
      id: '/_authenticated/_admin/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/roles': {
      id: '/_authenticated/_admin/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/sa-reports': {
      id: '/_authenticated/_admin/admin/sa-reports'
      path: '/sa-reports'
      fullPath: '/admin/sa-reports'
      preLoaderRoute: typeof AuthenticatedAdminAdminSaReportsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/security': {
      id: '/_authenticated/_admin/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/subscriptions': {
      id: '/_authenticated/_admin/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/system': {
      id: '/_authenticated/_admin/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/api/public/rules/v1': {
      id: '/api/public/rules/v1'
      path: '/api/public/rules/v1'
      fullPath: '/api/public/rules/v1'
      preLoaderRoute: typeof ApiPublicRulesV1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminAdminUsersRoute: typeof AuthenticatedAdminAdminAdminUsersRoute
  AuthenticatedAdminAdminAdsRoute: typeof AuthenticatedAdminAdminAdsRoute
  AuthenticatedAdminAdminAiMonitoringRoute: typeof AuthenticatedAdminAdminAiMonitoringRoute
  AuthenticatedAdminAdminAnalyticsRoute: typeof AuthenticatedAdminAdminAnalyticsRoute
  AuthenticatedAdminAdminApiRoute: typeof AuthenticatedAdminAdminApiRoute
  AuthenticatedAdminAdminAuditRoute: typeof AuthenticatedAdminAdminAuditRoute
  AuthenticatedAdminAdminBackupsRoute: typeof AuthenticatedAdminAdminBackupsRoute
  AuthenticatedAdminAdminBillingRoute: typeof AuthenticatedAdminAdminBillingRoute
  AuthenticatedAdminAdminCalculationAuditRoute: typeof AuthenticatedAdminAdminCalculationAuditRoute
  AuthenticatedAdminAdminCasesRoute: typeof AuthenticatedAdminAdminCasesRoute
  AuthenticatedAdminAdminCountriesRoute: typeof AuthenticatedAdminAdminCountriesRoute
  AuthenticatedAdminAdminFeaturesRoute: typeof AuthenticatedAdminAdminFeaturesRoute
  AuthenticatedAdminAdminKnowledgeRoute: typeof AuthenticatedAdminAdminKnowledgeRoute
  AuthenticatedAdminAdminLawyersRoute: typeof AuthenticatedAdminAdminLawyersRoute
  AuthenticatedAdminAdminLegalContentRoute: typeof AuthenticatedAdminAdminLegalContentRoute
  AuthenticatedAdminAdminLegalEngineRoute: typeof AuthenticatedAdminAdminLegalEngineRoute
  AuthenticatedAdminAdminLegalReferencesRoute: typeof AuthenticatedAdminAdminLegalReferencesRoute
  AuthenticatedAdminAdminLegalRulesRoute: typeof AuthenticatedAdminAdminLegalRulesRoute
  AuthenticatedAdminAdminNotificationsRoute: typeof AuthenticatedAdminAdminNotificationsRoute
  AuthenticatedAdminAdminOrganizationsRoute: typeof AuthenticatedAdminAdminOrganizationsRoute
  AuthenticatedAdminAdminOverviewRoute: typeof AuthenticatedAdminAdminOverviewRoute
  AuthenticatedAdminAdminPaymentsRoute: typeof AuthenticatedAdminAdminPaymentsRoute
  AuthenticatedAdminAdminPermissionsRoute: typeof AuthenticatedAdminAdminPermissionsRoute
  AuthenticatedAdminAdminReferralsRoute: typeof AuthenticatedAdminAdminReferralsRoute
  AuthenticatedAdminAdminReportTemplateRoute: typeof AuthenticatedAdminAdminReportTemplateRoute
  AuthenticatedAdminAdminReportsCenterRoute: typeof AuthenticatedAdminAdminReportsCenterRoute
  AuthenticatedAdminAdminReviewsRoute: typeof AuthenticatedAdminAdminReviewsRoute
  AuthenticatedAdminAdminRolesRoute: typeof AuthenticatedAdminAdminRolesRoute
  AuthenticatedAdminAdminSaReportsRoute: typeof AuthenticatedAdminAdminSaReportsRoute
  AuthenticatedAdminAdminSecurityRoute: typeof AuthenticatedAdminAdminSecurityRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminSubscriptionsRoute: typeof AuthenticatedAdminAdminSubscriptionsRoute
  AuthenticatedAdminAdminSystemRoute: typeof AuthenticatedAdminAdminSystemRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminAdminUsersRoute:
      AuthenticatedAdminAdminAdminUsersRoute,
    AuthenticatedAdminAdminAdsRoute: AuthenticatedAdminAdminAdsRoute,
    AuthenticatedAdminAdminAiMonitoringRoute:
      AuthenticatedAdminAdminAiMonitoringRoute,
    AuthenticatedAdminAdminAnalyticsRoute:
      AuthenticatedAdminAdminAnalyticsRoute,
    AuthenticatedAdminAdminApiRoute: AuthenticatedAdminAdminApiRoute,
    AuthenticatedAdminAdminAuditRoute: AuthenticatedAdminAdminAuditRoute,
    AuthenticatedAdminAdminBackupsRoute: AuthenticatedAdminAdminBackupsRoute,
    AuthenticatedAdminAdminBillingRoute: AuthenticatedAdminAdminBillingRoute,
    AuthenticatedAdminAdminCalculationAuditRoute:
      AuthenticatedAdminAdminCalculationAuditRoute,
    AuthenticatedAdminAdminCasesRoute: AuthenticatedAdminAdminCasesRoute,
    AuthenticatedAdminAdminCountriesRoute:
      AuthenticatedAdminAdminCountriesRoute,
    AuthenticatedAdminAdminFeaturesRoute: AuthenticatedAdminAdminFeaturesRoute,
    AuthenticatedAdminAdminKnowledgeRoute:
      AuthenticatedAdminAdminKnowledgeRoute,
    AuthenticatedAdminAdminLawyersRoute: AuthenticatedAdminAdminLawyersRoute,
    AuthenticatedAdminAdminLegalContentRoute:
      AuthenticatedAdminAdminLegalContentRoute,
    AuthenticatedAdminAdminLegalEngineRoute:
      AuthenticatedAdminAdminLegalEngineRoute,
    AuthenticatedAdminAdminLegalReferencesRoute:
      AuthenticatedAdminAdminLegalReferencesRoute,
    AuthenticatedAdminAdminLegalRulesRoute:
      AuthenticatedAdminAdminLegalRulesRoute,
    AuthenticatedAdminAdminNotificationsRoute:
      AuthenticatedAdminAdminNotificationsRoute,
    AuthenticatedAdminAdminOrganizationsRoute:
      AuthenticatedAdminAdminOrganizationsRoute,
    AuthenticatedAdminAdminOverviewRoute: AuthenticatedAdminAdminOverviewRoute,
    AuthenticatedAdminAdminPaymentsRoute: AuthenticatedAdminAdminPaymentsRoute,
    AuthenticatedAdminAdminPermissionsRoute:
      AuthenticatedAdminAdminPermissionsRoute,
    AuthenticatedAdminAdminReferralsRoute:
      AuthenticatedAdminAdminReferralsRoute,
    AuthenticatedAdminAdminReportTemplateRoute:
      AuthenticatedAdminAdminReportTemplateRoute,
    AuthenticatedAdminAdminReportsCenterRoute:
      AuthenticatedAdminAdminReportsCenterRoute,
    AuthenticatedAdminAdminReviewsRoute: AuthenticatedAdminAdminReviewsRoute,
    AuthenticatedAdminAdminRolesRoute: AuthenticatedAdminAdminRolesRoute,
    AuthenticatedAdminAdminSaReportsRoute:
      AuthenticatedAdminAdminSaReportsRoute,
    AuthenticatedAdminAdminSecurityRoute: AuthenticatedAdminAdminSecurityRoute,
    AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
    AuthenticatedAdminAdminSubscriptionsRoute:
      AuthenticatedAdminAdminSubscriptionsRoute,
    AuthenticatedAdminAdminSystemRoute: AuthenticatedAdminAdminSystemRoute,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCalculationsRoute: typeof AuthenticatedCalculationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLawyerDashboardRoute: typeof AuthenticatedLawyerDashboardRoute
  AuthenticatedMySubscriptionRoute: typeof AuthenticatedMySubscriptionRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSubscriptionHistoryRoute: typeof AuthenticatedSubscriptionHistoryRoute
  AuthenticatedSaAnnualLeaveRoute: typeof AuthenticatedSaAnnualLeaveRoute
  AuthenticatedSaCalculationEngineRoute: typeof AuthenticatedSaCalculationEngineRoute
  AuthenticatedSaCalculatorRoute: typeof AuthenticatedSaCalculatorRoute
  AuthenticatedSaCaseInfoRoute: typeof AuthenticatedSaCaseInfoRoute
  AuthenticatedSaCompensationRoute: typeof AuthenticatedSaCompensationRoute
  AuthenticatedSaContractsRoute: typeof AuthenticatedSaContractsRoute
  AuthenticatedSaEosbRoute: typeof AuthenticatedSaEosbRoute
  AuthenticatedSaFinalReportRoute: typeof AuthenticatedSaFinalReportRoute
  AuthenticatedSaFinalSettlementRoute: typeof AuthenticatedSaFinalSettlementRoute
  AuthenticatedSaMaternityRoute: typeof AuthenticatedSaMaternityRoute
  AuthenticatedSaSalaryRoute: typeof AuthenticatedSaSalaryRoute
  AuthenticatedSaSickLeaveRoute: typeof AuthenticatedSaSickLeaveRoute
  AuthenticatedSaSocialInsuranceRoute: typeof AuthenticatedSaSocialInsuranceRoute
  AuthenticatedSaTerminationRoute: typeof AuthenticatedSaTerminationRoute
  AuthenticatedSaTrialPeriodsRoute: typeof AuthenticatedSaTrialPeriodsRoute
  AuthenticatedSaUnpaidSalariesRoute: typeof AuthenticatedSaUnpaidSalariesRoute
  AuthenticatedSaWorkingHoursRoute: typeof AuthenticatedSaWorkingHoursRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCalculationsRoute: AuthenticatedCalculationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLawyerDashboardRoute: AuthenticatedLawyerDashboardRoute,
  AuthenticatedMySubscriptionRoute: AuthenticatedMySubscriptionRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSubscriptionHistoryRoute: AuthenticatedSubscriptionHistoryRoute,
  AuthenticatedSaAnnualLeaveRoute: AuthenticatedSaAnnualLeaveRoute,
  AuthenticatedSaCalculationEngineRoute: AuthenticatedSaCalculationEngineRoute,
  AuthenticatedSaCalculatorRoute: AuthenticatedSaCalculatorRoute,
  AuthenticatedSaCaseInfoRoute: AuthenticatedSaCaseInfoRoute,
  AuthenticatedSaCompensationRoute: AuthenticatedSaCompensationRoute,
  AuthenticatedSaContractsRoute: AuthenticatedSaContractsRoute,
  AuthenticatedSaEosbRoute: AuthenticatedSaEosbRoute,
  AuthenticatedSaFinalReportRoute: AuthenticatedSaFinalReportRoute,
  AuthenticatedSaFinalSettlementRoute: AuthenticatedSaFinalSettlementRoute,
  AuthenticatedSaMaternityRoute: AuthenticatedSaMaternityRoute,
  AuthenticatedSaSalaryRoute: AuthenticatedSaSalaryRoute,
  AuthenticatedSaSickLeaveRoute: AuthenticatedSaSickLeaveRoute,
  AuthenticatedSaSocialInsuranceRoute: AuthenticatedSaSocialInsuranceRoute,
  AuthenticatedSaTerminationRoute: AuthenticatedSaTerminationRoute,
  AuthenticatedSaTrialPeriodsRoute: AuthenticatedSaTrialPeriodsRoute,
  AuthenticatedSaUnpaidSalariesRoute: AuthenticatedSaUnpaidSalariesRoute,
  AuthenticatedSaWorkingHoursRoute: AuthenticatedSaWorkingHoursRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface LawyersRouteChildren {
  LawyersSlugRoute: typeof LawyersSlugRoute
}

const LawyersRouteChildren: LawyersRouteChildren = {
  LawyersSlugRoute: LawyersSlugRoute,
}

const LawyersRouteWithChildren =
  LawyersRoute._addFileChildren(LawyersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  DisclaimerRoute: DisclaimerRoute,
  DocumentSearchRoute: DocumentSearchRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LawyerRegisterRoute: LawyerRegisterRoute,
  LawyersRoute: LawyersRouteWithChildren,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PdfPreviewRoute: PdfPreviewRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectCountryRoute: SelectCountryRoute,
  SubscribeRoute: SubscribeRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPublicRulesV1Route: ApiPublicRulesV1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
